
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA EQUAL ID LBRACE LBRACKET NUMBER RBRACE RBRACKETstatement : assignmentassignment : ID EQUAL tabletable : LBRACE fields RBRACE\n| LBRACE RBRACEfields : fields COMMA fieldfields : fieldfield : ID EQUAL value\n| LBRACKET value RBRACKET EQUAL valuevalue : NUMBER\n| ID\n| table'
    
_lr_action_items = {'ID':([0,6,11,13,14,22,],[3,10,17,10,17,17,]),'$end':([1,2,5,8,12,],[0,-1,-2,-4,-3,]),'EQUAL':([3,10,21,],[4,14,22,]),'LBRACE':([4,11,14,22,],[6,6,6,6,]),'RBRACE':([6,7,8,9,12,16,17,18,19,20,23,],[8,12,-4,-6,-3,-9,-10,-11,-5,-7,-8,]),'LBRACKET':([6,13,],[11,11,]),'COMMA':([7,8,9,12,16,17,18,19,20,23,],[13,-4,-6,-3,-9,-10,-11,-5,-7,-8,]),'RBRACKET':([8,12,15,16,17,18,],[-4,-3,21,-9,-10,-11,]),'NUMBER':([11,14,22,],[16,16,16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'assignment':([0,],[2,]),'table':([4,11,14,22,],[5,18,18,18,]),'fields':([6,],[7,]),'field':([6,13,],[9,19,]),'value':([11,14,22,],[15,20,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> assignment','statement',1,'p_statement','tables_statement.py',47),
  ('assignment -> ID EQUAL table','assignment',3,'p_assignment','tables_statement.py',51),
  ('table -> LBRACE fields RBRACE','table',3,'p_table','tables_statement.py',55),
  ('table -> LBRACE RBRACE','table',2,'p_table','tables_statement.py',56),
  ('fields -> fields COMMA field','fields',3,'p_fields_multi','tables_statement.py',60),
  ('fields -> field','fields',1,'p_fields_single','tables_statement.py',64),
  ('field -> ID EQUAL value','field',3,'p_field','tables_statement.py',68),
  ('field -> LBRACKET value RBRACKET EQUAL value','field',5,'p_field','tables_statement.py',69),
  ('value -> NUMBER','value',1,'p_value','tables_statement.py',76),
  ('value -> ID','value',1,'p_value','tables_statement.py',77),
  ('value -> table','value',1,'p_value','tables_statement.py',78),
]
